/**
 * Seed Script — Properties
 * Run: node src/seed/seedProperties.js
 *
 * Inserts the 11 curated luxury listings into MongoDB.
 * Safe to re-run: skips if properties already exist.
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: resolve(__dirname, '../../.env') });

import Property from '../models/Property.js';

const properties = [
  {
    title: 'Aura Worli Sky Penthouse',
    type: 'Penthouse',
    category: 'Luxury Apartments',
    price: 450000000,
    priceLabel: '₹45 Cr',
    location: 'Worli, Mumbai',
    city: 'Mumbai',
    bedrooms: 5,
    bathrooms: 6,
    area: 6200,
    parking: 4,
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    ],
    badge: 'Featured',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Arabian Sea View', 'Private Elevator', 'Infinity Pool', 'Smart Automation', '24/7 Concierge', 'Four Parking Bays', 'Jacuzzi', 'Home Theatre'],
    description: "An extraordinary duplex penthouse situated high above Worli, Mumbai. Boasting unobstructed panoramic views of the Arabian Sea and the Bandra-Worli Sea Link. Custom Italian marble flooring, international appliances, and architectural grandeur meet to create Mumbai's most prestigious residence.",
    agent: { id: 1, name: 'Arjun Kapoor', phone: '+91 98765 43210' },
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'West Facing',
    developer: 'Lodha Group',
    rera: 'P51900010890',
    coordinates: { lat: 19.0178, lng: 72.8173 },
  },
  {
    title: 'The Banyan Estate',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 185000000,
    priceLabel: '₹18.5 Cr',
    location: 'Golf Course Road, Gurugram',
    city: 'Delhi NCR',
    bedrooms: 5,
    bathrooms: 6,
    area: 7800,
    parking: 4,
    image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
    ],
    badge: 'New Launch',
    badgeColor: 'green',
    status: 'Under Construction',
    featured: true,
    amenities: ['Private Lawn', 'Infinity Pool', 'Home Automation', 'Basement Theatre', 'Elevator', 'Gym', 'Staff Quarters', 'EV Charging Spot'],
    description: "A spectacular contemporary villa situated along the prestigious Golf Course Road corridor in Gurugram. Designed by leading international architects, this residence combines expansive double-height living areas, a private pool, and curated landscape gardens for ultimate luxury.",
    agent: { id: 2, name: 'Priya Sharma', phone: '+91 98765 43211' },
    yearBuilt: 2025,
    furnishing: 'Shell Condition',
    facing: 'North-East Facing',
    developer: 'DLF Limited',
    rera: 'HRERA2024GGM789',
    coordinates: { lat: 28.4389, lng: 77.0989 },
  },
  {
    title: 'Indiranagar Premium Duplex',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 58000000,
    priceLabel: '₹5.8 Cr',
    location: 'Indiranagar, Bengaluru',
    city: 'Bengaluru',
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1600607687644-c7171b46b83a?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1600607687644-c7171b46b83a?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    badge: 'Trending',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Private Terrace Garden', 'Clubhouse Access', 'Equipped Gym', 'Yoga Studio', '24/7 Security', 'High-Speed Elevators', 'Rooftop Lounge'],
    description: "An elegant duplex residence located in one of Bengaluru's greenest and most vibrant prime neighborhoods. Features floor-to-ceiling glass paneling, smart home controls, and a gorgeous landscaped private terrace garden.",
    agent: { id: 3, name: 'Rahul Mehta', phone: '+91 98765 43212' },
    yearBuilt: 2023,
    furnishing: 'Semi Furnished',
    facing: 'East Facing',
    developer: 'Prestige Group',
    rera: 'PRM/KA/RERA/1251/310/PR/180524',
    coordinates: { lat: 12.9719, lng: 77.6412 },
  },
  {
    title: 'The Jubilee Hills Manor',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 320000000,
    priceLabel: '₹32 Cr',
    location: 'Jubilee Hills, Hyderabad',
    city: 'Hyderabad',
    bedrooms: 6,
    bathrooms: 7,
    area: 9200,
    parking: 5,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    ],
    badge: 'Exclusive',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Private Infinity Pool', 'Meditation Pavilion', 'Home Cinema', 'Bespoke Wine Cellar', 'Professional Kitchen', 'Helipad Access', 'EV Chargers'],
    description: "A masterpiece of contemporary luxury real estate in Hyderabad's ultra-elite enclave of Jubilee Hills. Spanning 9,200 sqft of exquisite living spaces, this architectural marvel incorporates natural stone, pristine water bodies, and custom light installations.",
    agent: { id: 1, name: 'Arjun Kapoor', phone: '+91 98765 43210' },
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'North-East Facing',
    developer: 'Aurobindo Realty',
    rera: 'P02500001048',
    coordinates: { lat: 17.4325, lng: 78.4071 },
  },
  {
    title: 'Elysian Heights Koregaon Park',
    type: 'Penthouse',
    category: 'Luxury Apartments',
    price: 120000000,
    priceLabel: '₹12 Cr',
    location: 'Koregaon Park, Pune',
    city: 'Pune',
    bedrooms: 5,
    bathrooms: 5,
    area: 4800,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    ],
    badge: 'Featured',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Rooftop Deck', 'Smart Home Control', 'Italian Kitchen', 'Private Lounge', 'Valet Parking', 'Concierge Service'],
    description: "Located in Pune's most prestigious location — Koregaon Park. This penthouse features a private rooftop lounge, customized designer wardrobes, premium wellness spaces, and complete home automation by Crestron.",
    agent: { id: 4, name: 'Neha Gupta', phone: '+91 98765 43213' },
    yearBuilt: 2024,
    furnishing: 'Fully Furnished',
    facing: 'East Facing',
    developer: 'Panchshil Realty',
    rera: 'P52100046789',
    coordinates: { lat: 18.5362, lng: 73.8930 },
  },
  {
    title: 'Casa Miramar Beach Villa',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 150000000,
    priceLabel: '₹15 Cr',
    location: 'Candolim, Goa',
    city: 'Goa',
    bedrooms: 4,
    bathrooms: 5,
    area: 5500,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
      'https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80',
    ],
    badge: 'Beachfront',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Private Beach Access', 'Ocean-facing Deck', 'Infinity Pool', 'Sunset Lounge', 'EV Charging Station', 'Full Power Backup'],
    description: "A bespoke beachfront sanctuary in Candolim, Goa. Steps from the pristine sands, featuring private ocean-facing infinity pool, premium Goan architectural influences merged with modern styling, and expansive decks to enjoy the perfect sunset.",
    agent: { id: 2, name: 'Priya Sharma', phone: '+91 98765 43211' },
    yearBuilt: 2023,
    furnishing: 'Fully Furnished',
    facing: 'West Facing',
    developer: 'Vianaar Homes',
    rera: 'PRGO08230987',
    coordinates: { lat: 15.5164, lng: 73.7632 },
  },
  {
    title: 'Lutyens Heritage Mansion',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 950000000,
    priceLabel: '₹95 Cr',
    location: 'Lutyens Bungalow Zone, New Delhi',
    city: 'Delhi NCR',
    bedrooms: 6,
    bathrooms: 8,
    area: 12000,
    parking: 6,
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    ],
    badge: 'Heritage',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Imperial Gardens', 'Olympic Size Pool', 'Separate Banquet Hall', 'Smart Security System', 'Staff Housing (4 Rooms)', 'Private Study'],
    description: "A rare and prized heritage style estate in India's most power-packed residential zone — Lutyens Delhi. Built over a sprawling plot with manicured English lawns, classic colonial facades, high ceilings, and state-of-the-art modern comforts.",
    agent: { id: 3, name: 'Rahul Mehta', phone: '+91 98765 43212' },
    yearBuilt: 2021,
    furnishing: 'Fully Furnished',
    facing: 'North Facing',
    developer: 'DLF Luxury Homes',
    rera: 'Exempted (Heritage Site)',
    coordinates: { lat: 28.6090, lng: 77.2144 },
  },
  {
    title: 'The Whitefield Sky Villa',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 75000000,
    priceLabel: '₹7.5 Cr',
    location: 'Whitefield, Bengaluru',
    city: 'Bengaluru',
    bedrooms: 4,
    bathrooms: 4,
    area: 4200,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    ],
    badge: 'Hot Deal',
    badgeColor: 'red',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Sky Pool', 'Private Bar', 'Dedicated Concierge', 'Smart Lighting', 'EV Parking Bays', 'VRV Airconditioning'],
    description: "A stunning sky villa perched in the clouds of Whitefield. This spacious double-height apartment offers wrap-around balconies, private sky plunge pool, and customized automated interiors tailored for high-flying professionals.",
    agent: { id: 4, name: 'Neha Gupta', phone: '+91 98765 43213' },
    yearBuilt: 2024,
    furnishing: 'Semi Furnished',
    facing: 'East Facing',
    developer: 'Total Environment',
    rera: 'PRM/KA/RERA/1105/PR/200924',
    coordinates: { lat: 12.9698, lng: 77.7499 },
  },
  {
    title: 'Baner Highrise Signature',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 42000000,
    priceLabel: '₹4.2 Cr',
    location: 'Baner, Pune',
    city: 'Pune',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1560185893-a55cbc8c57e3?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e3?w=800&q=80',
      'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80',
    ],
    badge: 'New Launch',
    badgeColor: 'green',
    status: 'Under Construction',
    featured: false,
    amenities: ['Rooftop Pool', 'Co-working Lounge', 'Electric Car Charging', 'Concierge', 'Gym', '24/7 Security'],
    description: "A refined high-rise in Pune's burgeoning Baner tech corridor. Designed for the modern executive with co-working zones, rooftop infinity pool, and panoramic Sahyadri views — a rare blend of workspace convenience and luxury living.",
    agent: { id: 4, name: 'Neha Gupta', phone: '+91 98765 43213' },
    yearBuilt: 2026,
    furnishing: 'Shell Condition',
    facing: 'North Facing',
    developer: 'Kumar Properties',
    rera: 'P52100050123',
    coordinates: { lat: 18.5590, lng: 73.7797 },
  },
  {
    title: 'Alibaug Coastal Retreat',
    type: 'Villa',
    category: 'Luxury Villas',
    price: 95000000,
    priceLabel: '₹9.5 Cr',
    location: 'Alibaug, Maharashtra',
    city: 'Mumbai',
    bedrooms: 4,
    bathrooms: 4,
    area: 6000,
    parking: 3,
    image: 'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?w=800&q=80',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80',
    ],
    badge: 'Exclusive',
    badgeColor: 'gold',
    status: 'Ready to Move',
    featured: true,
    amenities: ['Private Jetty Access', 'Saltwater Pool', 'Organic Garden', 'Chef\'s Kitchen', 'Bonfire Pit', 'Kids Play Zone'],
    description: "A secluded coastal estate in Alibaug — Mumbai's favourite weekend destination. This stunning retreat features a private jetty, saltwater pool, lush organic gardens, and uninterrupted views of the Arabian Sea.",
    agent: { id: 1, name: 'Arjun Kapoor', phone: '+91 98765 43210' },
    yearBuilt: 2022,
    furnishing: 'Fully Furnished',
    facing: 'West Facing',
    developer: 'Naiknavare Developers',
    rera: 'P51800030012',
    coordinates: { lat: 18.6584, lng: 72.8777 },
  },
  {
    title: 'Kalyani Nagar Sky Residence',
    type: 'Apartment',
    category: 'Luxury Apartments',
    price: 68000000,
    priceLabel: '₹6.8 Cr',
    location: 'Kalyani Nagar, Pune',
    city: 'Pune',
    bedrooms: 4,
    bathrooms: 4,
    area: 3400,
    parking: 2,
    image: 'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=800&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
    ],
    badge: 'Trending',
    badgeColor: 'blue',
    status: 'Ready to Move',
    featured: false,
    amenities: ['Sky Deck', 'Wine Room', 'Professional Gym', 'Steam & Sauna', 'Visitor Lounge', 'Power Backup'],
    description: "Positioned atop one of Kalyani Nagar's most sought-after towers, this 4BHK sky residence offers sweeping views of Pune's skyline. Interiors crafted by award-winning designers with Italian marble, smart controls, and a private sky deck.",
    agent: { id: 4, name: 'Neha Gupta', phone: '+91 98765 43213' },
    yearBuilt: 2024,
    furnishing: 'Semi Furnished',
    facing: 'South-West Facing',
    developer: 'Kolte Patil Developers',
    rera: 'P52100047856',
    coordinates: { lat: 18.5463, lng: 73.9033 },
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ MongoDB connected');

    // Clean up existing properties so coordinates are loaded correctly!
    await Property.deleteMany({});
    console.log('🧹 Cleared existing properties database');

    const inserted = await Property.insertMany(properties);
    console.log(`🏠 Seeded ${inserted.length} properties successfully with coordinates!`);
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 MongoDB disconnected');
  }
}

seed();
